#' @title Integration site annotation by gene data
#' 
#' @description \preformatted{
#' This data is generated by annoByGene function on random set analysis mode. 
#' Plus, it is used in example code of \code{drawingKaryo} and \code{makeDocument}.
#' }
#' 
#' @docType data
#' 
#' @usage 
#' data(blast_gene)
#' 
#' @format List object  
#' 
#' @examples 
#' data(blast_gene)
#' 
"blast_gene"